### PR TITLE
Allow selecting the entire output using the standard shortcut

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by mike-engel** [comment]
Hi @revolter, can you add a little more detail on why this change is needed? What is the standard shortcut you referenced in the title?

**Comment by revolter** [comment]
> What is the standard shortcut you referenced in the title?

<kbd>cmd</kbd> / <kbd>ctrl</kbd> + <kbd>a</kbd>

> Can you add a little more detail on why this change is needed?

It currently works like this:

---

image

---

And with my PR it works like this:

---

image

---

**Comment by mike-engel** [comment]
Thanks @revolter!

**Comment by revolter** [comment]
Thanks for merging ❤️

**Pull request merged**
